/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhitepaperRouteImport } from './routes/whitepaper'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TopWalletsRouteImport } from './routes/top-wallets'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as DecoderRouteImport } from './routes/decoder'
import { Route as IndexRouteImport } from './routes/index'

const WhitepaperRoute = WhitepaperRouteImport.update({
  id: '/whitepaper',
  path: '/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TopWalletsRoute = TopWalletsRouteImport.update({
  id: '/top-wallets',
  path: '/top-wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const DecoderRoute = DecoderRouteImport.update({
  id: '/decoder',
  path: '/decoder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decoder': typeof DecoderRoute
  '/simulator': typeof SimulatorRoute
  '/top-wallets': typeof TopWalletsRoute
  '/wallet': typeof WalletRoute
  '/whitepaper': typeof WhitepaperRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decoder': typeof DecoderRoute
  '/simulator': typeof SimulatorRoute
  '/top-wallets': typeof TopWalletsRoute
  '/wallet': typeof WalletRoute
  '/whitepaper': typeof WhitepaperRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decoder': typeof DecoderRoute
  '/simulator': typeof SimulatorRoute
  '/top-wallets': typeof TopWalletsRoute
  '/wallet': typeof WalletRoute
  '/whitepaper': typeof WhitepaperRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/decoder'
    | '/simulator'
    | '/top-wallets'
    | '/wallet'
    | '/whitepaper'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/decoder'
    | '/simulator'
    | '/top-wallets'
    | '/wallet'
    | '/whitepaper'
  id:
    | '__root__'
    | '/'
    | '/decoder'
    | '/simulator'
    | '/top-wallets'
    | '/wallet'
    | '/whitepaper'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecoderRoute: typeof DecoderRoute
  SimulatorRoute: typeof SimulatorRoute
  TopWalletsRoute: typeof TopWalletsRoute
  WalletRoute: typeof WalletRoute
  WhitepaperRoute: typeof WhitepaperRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whitepaper': {
      id: '/whitepaper'
      path: '/whitepaper'
      fullPath: '/whitepaper'
      preLoaderRoute: typeof WhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-wallets': {
      id: '/top-wallets'
      path: '/top-wallets'
      fullPath: '/top-wallets'
      preLoaderRoute: typeof TopWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decoder': {
      id: '/decoder'
      path: '/decoder'
      fullPath: '/decoder'
      preLoaderRoute: typeof DecoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecoderRoute: DecoderRoute,
  SimulatorRoute: SimulatorRoute,
  TopWalletsRoute: TopWalletsRoute,
  WalletRoute: WalletRoute,
  WhitepaperRoute: WhitepaperRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
